### ISSUE TITLE
Unable to parse nested Sass-Maps

### ISSUE THREAD

**Issue by 3rd-Eden** [jgranstrom/sass-extract#3] opened 2017-03-21 19:03 UTC
```
$palette: (
  white: (
    base: (color: #fff, contrast: #2b2b2b)
  ),
  black: (
    base: (color: #111, contrast: #fff),
    dark: (color: #000, contrast: #fff)
  )
) !default;
```

Attempting to parse this yields a JavaScript error stating that .getValue() is not a function. It originates from https://github.com/jgranstrom/sass-extract/blob/master/src/struct.js#L54

**Comment by jgranstrom** [comment] 2017-03-21 22:24
Thank you for the report! I will have a look asap.

**Comment by 3rd-Eden** [comment] 2017-03-21 22:55
@jgranstrom I managed to hack around it using: https://github.com/3rd-Eden/sass-extract/commit/d6604692875cac99e2b0688504c45e85af3c3465#diff-f52bb8aabd2ae3afd6fbc45f0ec4011cR56

But I just don't understand why SassMap.getLength() would return another item if there's nothing left. It kinda feels like bug in node-sass instead.

**Comment by jgranstrom** [comment] 2017-03-22 09:22
The problem in this case is that the nested keys are actually not strings, but `SassColor`, due to `white` and `black` are both representing color types. Since sass support map keys of any data type (exciting right? :) ), and sass-extract currently expects them to be strings, the extraction fails. I will look into how to represent keys of arbitrary data type for the next update.

For now your specific issue can be resolved by updating the sass map like so:
```
$palette: (
  'white': (
    base: (color: #fff, contrast: #2b2b2b)
  ),
  'black': (
    base: (color: #111, contrast: #fff),
    dark: (color: #000, contrast: #fff)
  )
) !default;
```

With single quoted keys, to ensure that they are treated as strings by libsass.

**Comment by jgranstrom** [comment] 2017-03-22 09:25
Since the nesting itself works, and the problem is the data types of the map keys, I will close this issue in favor for #4 which will track the data type of keys issue. Thanks!

**Closed by jgranstrom** 2017-03-22 09:25 UTC

**Comment by 3rd-Eden** [comment] 2017-03-22 13:16
Ha, I should have had my email open to get this notification. I just came to exactly the same conclusion while digging deeper in to the root cause here.

**Comment by 3rd-Eden** [comment] 2017-03-22 13:52
@jgranstrom While wrapping the map key's with single quotes is a solution to prevent the parser from crashing it's a breaking change to the SCSS map keys as `map-get($palette, white)` no longer works as it will now return `null`. It requires you to change the map lookups to `map-get($palette, 'white')` instead. Not really a problem for a small code base, but it's a massive pain for the for the scale of SCSS files i'm currently working with.

**Comment by jgranstrom** [comment] 2017-03-22 15:32
@3rd-Eden I agree it can definitely be a pain to work around by changing the SCSS. Unfortunately there is no real trivial solution as the SassColor is only containing native color data like RGBA, so it is not obvious how to key the extracted map. For the color example one alternative would be to key by the color hex so the map keys in this case would be `#000000` and `#FFFFFF` instead of black and white, it is however not optimal and does not translate well to the other types. Another alternative would be to use the raw expression as key, and bypass the libsass data types, but that also comes with a lot of cons. I will do some thinking tonight and try to come up with a reasonable option that does not require changing the SCSS source.

**Comment by 3rd-Eden** [comment] 2017-03-22 15:35
@jgranstrom Yep, I think the only suitable solution here would be a fix in `node-sass` to allow access to the raw value that was originally set as color. So color names can stay the same instead of being transformed into RGB strings or HEX values.
